name: simple home CI

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: simple_home_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11.2' # Define the elixir version [required]
        otp-version: '23.1' # Define the OTP version [required]
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install chromedriver
      run: |
          CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip 
          unzip chromedriver_linux64.zip
          rm chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver
   


    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get

    - name: check linting
      run: mix check_lint

    - name: Setup db
      run: mix ecto.create
      
    - name: Run tests
      run: mix test
    - name: Run test coverage
      run: mix coveralls
